from optimized_job_bot import OptimizedJobBot

print("🚀 Starting OPTIMIZED Job Bot - WORKING PLATFORMS ONLY!")
print("=" * 70)
print("🎯 Target: 50+ applications guaranteed")
print("⚡ Speed: Optimized for fast applications")
print("")
print("📊 WORKING PLATFORMS (7):")
print("   1. ✅ X Jobs (Twitter Careers) - careers.x.com/en")
print("   2. ✅ RemoteOK (API + Templates) - remoteok.io")
print("   3. ✅ FlexJobs (Login Working) - flexjobs.com")
print("   4. ✅ DICE (Tech Jobs) - dice.com")
print("   5. ✅ Indeed (Job Templates) - indeed.com")
print("   6. ✅ WeWorkRemotely (Remote Jobs) - weworkremotely.com")
print("   7. ✅ Turing (Developer Jobs) - developers.turing.com")
print("")
print("❌ REMOVED NON-WORKING PLATFORMS:")
print("   ❌ LinkedIn (Login issues)")
print("   ❌ Glassdoor (Protected site)")
print("   ❌ Monster (Navigation issues)")
print("   ❌ ZipRecruiter (Protected site)")
print("")
print("🔥 OPTIMIZED FEATURES:")
print("   • 60+ job templates across working platforms")
print("   • 🚫 NO DUPLICATE APPLICATIONS (smart filtering)")
print("   • ⏱️ RANDOM DELAYS (10-15 sec between apps)")
print("   • Screenshot proof for every application")
print("   • Custom cover letters for each job")
print("   • Real API integration with RemoteOK")
print("   • Persistent job history tracking")
print("   • Human-like application behavior")
print("")
print("📧 CREDENTIALS:")
print("   • FlexJobs: rj691957@gmail.com")
print("   • Other platforms: Template applications")
print("")
print("📸 PROOF SYSTEM:")
print("   • Screenshots saved in application_proofs/")
print("   • Application logs in optimized_applications.txt")
print("   • Cycle logs in optimized_cycle_log.txt")
print("")
print("⏱️ ESTIMATED TIME: 5-10 minutes for 50+ applications")
print("=" * 70)
print("🚀 LAUNCHING OPTIMIZED BOT...")

bot = OptimizedJobBot()
bot.run_optimized_cycle()
